name: lakbayan
description: TARA LAAG
publish_to: 'none'
version: 1.0.0+1

environment:  
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_database: ^10.2.5
  excel: ^2.1.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.6
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.7
  location: ^4.4.0
  flutter_svg: ^1.1.0
  geocoding: ^2.1.0
  cloud_firestore: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/fonts/
    - assets/
    - assets/icons/
  fonts:
    - family: Nunito
      fonts:
        - asset: lib/fonts/Nunito-Regular.ttf
        - asset: lib/fonts/Nunito-Bold.ttf
          weight: 700

